package com.mobicom.s16.mco.domain.model

data class Card(
    val id: String = "",
    val isArchived: Boolean = false,
    val name: String = "",
    val supertype: String = "",
    val subtypes: List<String>? = emptyList(),
    val hp: String? = "",
    val types: List<String>? = emptyList(),
    val evolvesFrom: String? = "",
    val evolvesTo: List<String>? = emptyList(),
    val attacks: List<Attack>? = emptyList(),
    val abilities: List<Ability>? = emptyList(),
    val weaknesses: List<Weakness>? = emptyList(),
    val resistances: List<Resistance>? = emptyList(),
    val retreatCost: List<String>? = emptyList(),
    val convertedRetreatCost: Int? = 0,
    val set: String = "",
    val setId: String = "",
    val setSeries: String = "",
    val number: String = "",
    val artist: String? = "",
    val rarity: String? = "",
    val flavorText: String? = "",
    val imageUrl: String = "",
    val imageUrlLarge: String = "",
    val price: Double = 0.0,
    val priceSource: String = "tcgplayer" // or "cardmarket"
)
